# import = ["~/.config/alacritty/themes/everforest-alacritty-theme.toml",]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#5A524C"
duration = 100

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/bin/zsh"

[window]
decorations = "Full"
dynamic_padding = true
dynamic_title = true
opacity = 0.93

[window.padding]
x = 5
y = 5

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[colors.primary]
background = "#272E33"
foreground = "#d3c6aa"

[colors.normal]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"
