# Zenbones Light

[colors.bright]
black = "#CFC1BA"
red = "#94253E"
green = "#3F5A22"
yellow = "#803D1C"
blue = "#1D5573"
magenta = "#7B3B70"
cyan = "#2B747C"
white = "#4F5E68"

[colors.cursor]
cursor = "#2C363C"
text = "#E8E4E3"

[colors.normal]
black = "#E8E4E3"
blue = "#286486"
cyan = "#3B8992"
green = "#4F6C31"
magenta = "#88507D"
red = "#A8334C"
white = "#2C363C"
yellow = "#944927"

[colors.primary]
background = "#E8E4E3"
foreground = "#2C363C"
