# Zenwritten Light

[colors.bright]
black = "#C6C3C3"
red = "#94253E"
green = "#3F5A22"
yellow = "#803D1C"
blue = "#1D5573"
magenta = "#7B3B70"
cyan = "#2B747C"
white = "#5C5C5C"

[colors.cursor]
cursor = "#353535"
text = "#EEEEEE"

[colors.normal]
black = "#EEEEEE"
blue = "#286486"
cyan = "#3B8992"
green = "#4F6C31"
magenta = "#88507D"
red = "#A8334C"
white = "#353535"
yellow = "#944927"

[colors.primary]
background = "#EEEEEE"
foreground = "#353535"
