[font]
size = 12
# offset = { x = 0, y = 3 }

[font.bold]
family = "Maple Mono"
style = "Bold"

[font.bold_italic]
family = "Maple Mono"
style = "Bold Italic"

[font.italic]
family = "Maple Mono"
style = "Italic"

[font.normal]
family = "Maple Mono"
style = "Regular"
