[font]
size = 12
offset = { x = 0, y = 3 }

[font.bold]
family = "Monolisa"
style = "Bold"

[font.bold_italic]
family = "Monolisa"
style = "Bold Italic"

[font.italic]
family = "Monolisa"
style = "Italic"

[font.normal]
family = "Monolisa"
style = "Book"
