general.import = ["~/.config/alacritty/themes/poimandres-alacritty-theme.toml"]
general.live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#767C9D"
duration = 100

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "None"
padding = { x = 3, y = 3 }
dynamic_padding = true
dynamic_title = true
opacity = 0.94

[font]
size = 12

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Medium"
