general.import = ["~/.config/alacritty/themes/tokyonight_night-alacritty.toml"]
general.live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#5A524C"
duration = 100

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "Full"
dynamic_padding = true
dynamic_title = true
opacity = 0.93

[window.padding]
x = 5
y = 5

[font]
size = 12

[font.bold]
family = "JetBrainsMonoNL NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL NF"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Medium"

[terminal]
