general.live_config_reload = true

general.import = [
  "~/.config/alacritty/themes/current-theme.toml",
  "~/.config/alacritty/fonts/JetBrainsMonoNL-alacritty-font.toml",
]

[bell]
animation = "EaseOutExpo"
color = "#767C9D"
duration = 100

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/bin/fish"

[window]
decorations = "none"
padding = { x = 5, y = 3 }
dynamic_padding = true
dynamic_title = true
opacity = 1
